/**
 * This class is generated by jOOQ
 */
package com.pokupaka.dao.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pokupaka extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1653052970;

	/**
	 * The singleton instance of <code>pokupaka</code>
	 */
	public static final Pokupaka POKUPAKA = new Pokupaka();

	/**
	 * No further instances allowed
	 */
	private Pokupaka() {
		super("pokupaka");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.pokupaka.dao.jooq.tables.Camera.CAMERA,
			com.pokupaka.dao.jooq.tables.User.USER);
	}
}
