/**
 * This class is generated by jOOQ
 */
package com.pokupaka.dao.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in pokupaka
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table pokupaka.Camera
	 */
	public static final com.pokupaka.dao.jooq.tables.Camera CAMERA = com.pokupaka.dao.jooq.tables.Camera.CAMERA;

	/**
	 * The table pokupaka.User
	 */
	public static final com.pokupaka.dao.jooq.tables.User USER = com.pokupaka.dao.jooq.tables.User.USER;
}
