/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cameragroup extends org.jooq.impl.TableImpl<com.selfach.dao.jooq.tables.records.CameragroupRecord> {

	private static final long serialVersionUID = -1197484323;

	/**
	 * The singleton instance of <code>selfach.CameraGroup</code>
	 */
	public static final com.selfach.dao.jooq.tables.Cameragroup CAMERAGROUP = new com.selfach.dao.jooq.tables.Cameragroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.selfach.dao.jooq.tables.records.CameragroupRecord> getRecordType() {
		return com.selfach.dao.jooq.tables.records.CameragroupRecord.class;
	}

	/**
	 * The column <code>selfach.CameraGroup.id</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.CameragroupRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>selfach.CameraGroup.name</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.CameragroupRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(33), this, "");

	/**
	 * Create a <code>selfach.CameraGroup</code> table reference
	 */
	public Cameragroup() {
		this("CameraGroup", null);
	}

	/**
	 * Create an aliased <code>selfach.CameraGroup</code> table reference
	 */
	public Cameragroup(java.lang.String alias) {
		this(alias, com.selfach.dao.jooq.tables.Cameragroup.CAMERAGROUP);
	}

	private Cameragroup(java.lang.String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.CameragroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cameragroup(java.lang.String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.CameragroupRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.selfach.dao.jooq.Selfach.SELFACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameragroupRecord> getPrimaryKey() {
		return com.selfach.dao.jooq.Keys.KEY_CAMERAGROUP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameragroupRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameragroupRecord>>asList(com.selfach.dao.jooq.Keys.KEY_CAMERAGROUP_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.selfach.dao.jooq.tables.Cameragroup as(java.lang.String alias) {
		return new com.selfach.dao.jooq.tables.Cameragroup(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.selfach.dao.jooq.tables.Cameragroup rename(java.lang.String name) {
		return new com.selfach.dao.jooq.tables.Cameragroup(name, null);
	}
}
