/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cameraraiting extends org.jooq.impl.TableImpl<com.selfach.dao.jooq.tables.records.CameraraitingRecord> {

	private static final long serialVersionUID = -873507034;

	/**
	 * The singleton instance of <code>selfach.CameraRaiting</code>
	 */
	public static final Cameraraiting CAMERARAITING = new Cameraraiting();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<com.selfach.dao.jooq.tables.records.CameraraitingRecord> getRecordType() {
		return com.selfach.dao.jooq.tables.records.CameraraitingRecord.class;
	}

	/**
	 * The column <code>selfach.CameraRaiting.id</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.CameraraitingRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>selfach.CameraRaiting.cameraId</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.CameraraitingRecord, Integer> CAMERAID = createField("cameraId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>selfach.CameraRaiting.raiting</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.CameraraitingRecord, Integer> RAITING = createField("raiting", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>selfach.CameraRaiting</code> table reference
	 */
	public Cameraraiting() {
		this("CameraRaiting", null);
	}

	/**
	 * Create an aliased <code>selfach.CameraRaiting</code> table reference
	 */
	public Cameraraiting(String alias) {
		this(alias, Cameraraiting.CAMERARAITING);
	}

	private Cameraraiting(String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.CameraraitingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cameraraiting(String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.CameraraitingRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.selfach.dao.jooq.Selfach.SELFACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.selfach.dao.jooq.tables.records.CameraraitingRecord, Integer> getIdentity() {
		return com.selfach.dao.jooq.Keys.IDENTITY_CAMERARAITING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraraitingRecord> getPrimaryKey() {
		return com.selfach.dao.jooq.Keys.KEY_CAMERARAITING_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraraitingRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraraitingRecord>>asList(com.selfach.dao.jooq.Keys.KEY_CAMERARAITING_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.CameraraitingRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.CameraraitingRecord, ?>>asList(com.selfach.dao.jooq.Keys.CAMERARAITING_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Cameraraiting as(String alias) {
		return new Cameraraiting(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Cameraraiting rename(String name) {
		return new Cameraraiting(name, null);
	}
}
