/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Camerarating extends org.jooq.impl.TableImpl<com.selfach.dao.jooq.tables.records.CameraratingRecord> {

	private static final long serialVersionUID = 605883101;

	/**
	 * The singleton instance of <code>selfach.CameraRating</code>
	 */
	public static final com.selfach.dao.jooq.tables.Camerarating CAMERARATING = new com.selfach.dao.jooq.tables.Camerarating();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.selfach.dao.jooq.tables.records.CameraratingRecord> getRecordType() {
		return com.selfach.dao.jooq.tables.records.CameraratingRecord.class;
	}

	/**
	 * The column <code>selfach.CameraRating.id</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.CameraratingRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>selfach.CameraRating.cameraId</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.CameraratingRecord, java.lang.Integer> CAMERAID = createField("cameraId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>selfach.CameraRating.userId</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.CameraratingRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>selfach.CameraRating.raiting</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.CameraratingRecord, java.lang.Integer> RAITING = createField("raiting", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>selfach.CameraRating</code> table reference
	 */
	public Camerarating() {
		this("CameraRating", null);
	}

	/**
	 * Create an aliased <code>selfach.CameraRating</code> table reference
	 */
	public Camerarating(java.lang.String alias) {
		this(alias, com.selfach.dao.jooq.tables.Camerarating.CAMERARATING);
	}

	private Camerarating(java.lang.String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.CameraratingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Camerarating(java.lang.String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.CameraratingRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.selfach.dao.jooq.Selfach.SELFACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.selfach.dao.jooq.tables.records.CameraratingRecord, java.lang.Integer> getIdentity() {
		return com.selfach.dao.jooq.Keys.IDENTITY_CAMERARATING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraratingRecord> getPrimaryKey() {
		return com.selfach.dao.jooq.Keys.KEY_CAMERARATING_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraratingRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraratingRecord>>asList(com.selfach.dao.jooq.Keys.KEY_CAMERARATING_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.CameraratingRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.CameraratingRecord, ?>>asList(com.selfach.dao.jooq.Keys.CAMERARATING_IBFK_1, com.selfach.dao.jooq.Keys.CAMERARATING_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.selfach.dao.jooq.tables.Camerarating as(java.lang.String alias) {
		return new com.selfach.dao.jooq.tables.Camerarating(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.selfach.dao.jooq.tables.Camerarating rename(java.lang.String name) {
		return new com.selfach.dao.jooq.tables.Camerarating(name, null);
	}
}
