/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<com.selfach.dao.jooq.tables.records.UserRecord> {

	private static final long serialVersionUID = -1918449189;

	/**
	 * The singleton instance of <code>selfach.User</code>
	 */
	public static final User USER = new User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<com.selfach.dao.jooq.tables.records.UserRecord> getRecordType() {
		return com.selfach.dao.jooq.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>selfach.User.id</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.UserRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>selfach.User.name</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.UserRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(22).defaulted(true), this, "");

	/**
	 * The column <code>selfach.User.surname</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.UserRecord, String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.VARCHAR.length(22).defaulted(true), this, "");

	/**
	 * The column <code>selfach.User.passwordHash</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.UserRecord, String> PASSWORDHASH = createField("passwordHash", org.jooq.impl.SQLDataType.VARCHAR.length(44), this, "");

	/**
	 * The column <code>selfach.User.email</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.UserRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(22), this, "");

	/**
	 * The column <code>selfach.User.created</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.UserRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>selfach.User.modified</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.UserRecord, java.sql.Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>selfach.User</code> table reference
	 */
	public User() {
		this("User", null);
	}

	/**
	 * Create an aliased <code>selfach.User</code> table reference
	 */
	public User(String alias) {
		this(alias, User.USER);
	}

	private User(String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.selfach.dao.jooq.Selfach.SELFACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.selfach.dao.jooq.tables.records.UserRecord, Integer> getIdentity() {
		return com.selfach.dao.jooq.Keys.IDENTITY_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.UserRecord> getPrimaryKey() {
		return com.selfach.dao.jooq.Keys.KEY_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.UserRecord>>asList(com.selfach.dao.jooq.Keys.KEY_USER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public User as(String alias) {
		return new User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public User rename(String name) {
		return new User(name, null);
	}
}
