/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Selfach extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1873147816;

	/**
	 * The singleton instance of <code>selfach</code>
	 */
	public static final Selfach SELFACH = new Selfach();

	/**
	 * No further instances allowed
	 */
	private Selfach() {
		super("selfach");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.selfach.dao.jooq.tables.Camera.CAMERA,
			com.selfach.dao.jooq.tables.Cameraraiting.CAMERARAITING,
			com.selfach.dao.jooq.tables.Photo.PHOTO,
			com.selfach.dao.jooq.tables.User.USER);
	}
}
