---
# tasks file for java8
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  command: add-apt-repository -y ppa:webupd8team/java

- name: Add FFMpeg Repository
  command: add-apt-repository -y ppa:kirillshkrogalev/ffmpeg-next

- name: Accept Java 8 Licence
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance
  
- name: update
  apt: update_cache=yes
  
- name: Install Oracle Java 8
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
    - ffmpeg