/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>selfach</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.selfach.dao.jooq.tables.records.CameraRecord, java.lang.Integer> IDENTITY_CAMERA = Identities0.IDENTITY_CAMERA;
	public static final org.jooq.Identity<com.selfach.dao.jooq.tables.records.CameraratingRecord, java.lang.Integer> IDENTITY_CAMERARATING = Identities0.IDENTITY_CAMERARATING;
	public static final org.jooq.Identity<com.selfach.dao.jooq.tables.records.PhotoRecord, java.lang.Integer> IDENTITY_PHOTO = Identities0.IDENTITY_PHOTO;
	public static final org.jooq.Identity<com.selfach.dao.jooq.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraRecord> KEY_CAMERA_PRIMARY = UniqueKeys0.KEY_CAMERA_PRIMARY;
	public static final org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraratingRecord> KEY_CAMERARATING_PRIMARY = UniqueKeys0.KEY_CAMERARATING_PRIMARY;
	public static final org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.PhotoRecord> KEY_PHOTO_PRIMARY = UniqueKeys0.KEY_PHOTO_PRIMARY;
	public static final org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.CameraratingRecord, com.selfach.dao.jooq.tables.records.CameraRecord> CAMERARATING_IBFK_1 = ForeignKeys0.CAMERARATING_IBFK_1;
	public static final org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.CameraratingRecord, com.selfach.dao.jooq.tables.records.UserRecord> CAMERARATING_IBFK_2 = ForeignKeys0.CAMERARATING_IBFK_2;
	public static final org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.PhotoRecord, com.selfach.dao.jooq.tables.records.UserRecord> PHOTO_IBFK_1 = ForeignKeys0.PHOTO_IBFK_1;
	public static final org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.PhotoRecord, com.selfach.dao.jooq.tables.records.CameraRecord> PHOTO_IBFK_2 = ForeignKeys0.PHOTO_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.selfach.dao.jooq.tables.records.CameraRecord, java.lang.Integer> IDENTITY_CAMERA = createIdentity(com.selfach.dao.jooq.tables.Camera.CAMERA, com.selfach.dao.jooq.tables.Camera.CAMERA.ID);
		public static org.jooq.Identity<com.selfach.dao.jooq.tables.records.CameraratingRecord, java.lang.Integer> IDENTITY_CAMERARATING = createIdentity(com.selfach.dao.jooq.tables.Camerarating.CAMERARATING, com.selfach.dao.jooq.tables.Camerarating.CAMERARATING.ID);
		public static org.jooq.Identity<com.selfach.dao.jooq.tables.records.PhotoRecord, java.lang.Integer> IDENTITY_PHOTO = createIdentity(com.selfach.dao.jooq.tables.Photo.PHOTO, com.selfach.dao.jooq.tables.Photo.PHOTO.ID);
		public static org.jooq.Identity<com.selfach.dao.jooq.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = createIdentity(com.selfach.dao.jooq.tables.User.USER, com.selfach.dao.jooq.tables.User.USER.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraRecord> KEY_CAMERA_PRIMARY = createUniqueKey(com.selfach.dao.jooq.tables.Camera.CAMERA, com.selfach.dao.jooq.tables.Camera.CAMERA.ID);
		public static final org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.CameraratingRecord> KEY_CAMERARATING_PRIMARY = createUniqueKey(com.selfach.dao.jooq.tables.Camerarating.CAMERARATING, com.selfach.dao.jooq.tables.Camerarating.CAMERARATING.ID);
		public static final org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.PhotoRecord> KEY_PHOTO_PRIMARY = createUniqueKey(com.selfach.dao.jooq.tables.Photo.PHOTO, com.selfach.dao.jooq.tables.Photo.PHOTO.ID);
		public static final org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.UserRecord> KEY_USER_PRIMARY = createUniqueKey(com.selfach.dao.jooq.tables.User.USER, com.selfach.dao.jooq.tables.User.USER.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.CameraratingRecord, com.selfach.dao.jooq.tables.records.CameraRecord> CAMERARATING_IBFK_1 = createForeignKey(com.selfach.dao.jooq.Keys.KEY_CAMERA_PRIMARY, com.selfach.dao.jooq.tables.Camerarating.CAMERARATING, com.selfach.dao.jooq.tables.Camerarating.CAMERARATING.CAMERAID);
		public static final org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.CameraratingRecord, com.selfach.dao.jooq.tables.records.UserRecord> CAMERARATING_IBFK_2 = createForeignKey(com.selfach.dao.jooq.Keys.KEY_USER_PRIMARY, com.selfach.dao.jooq.tables.Camerarating.CAMERARATING, com.selfach.dao.jooq.tables.Camerarating.CAMERARATING.USERID);
		public static final org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.PhotoRecord, com.selfach.dao.jooq.tables.records.UserRecord> PHOTO_IBFK_1 = createForeignKey(com.selfach.dao.jooq.Keys.KEY_USER_PRIMARY, com.selfach.dao.jooq.tables.Photo.PHOTO, com.selfach.dao.jooq.tables.Photo.PHOTO.USERID);
		public static final org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.PhotoRecord, com.selfach.dao.jooq.tables.records.CameraRecord> PHOTO_IBFK_2 = createForeignKey(com.selfach.dao.jooq.Keys.KEY_CAMERA_PRIMARY, com.selfach.dao.jooq.tables.Photo.PHOTO, com.selfach.dao.jooq.tables.Photo.PHOTO.CAMERAID);
	}
}
