/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in selfach
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table selfach.Camera
	 */
	public static final com.selfach.dao.jooq.tables.Camera CAMERA = com.selfach.dao.jooq.tables.Camera.CAMERA;

	/**
	 * The table selfach.CameraRating
	 */
	public static final com.selfach.dao.jooq.tables.Camerarating CAMERARATING = com.selfach.dao.jooq.tables.Camerarating.CAMERARATING;

	/**
	 * The table selfach.Photo
	 */
	public static final com.selfach.dao.jooq.tables.Photo PHOTO = com.selfach.dao.jooq.tables.Photo.PHOTO;

	/**
	 * The table selfach.User
	 */
	public static final com.selfach.dao.jooq.tables.User USER = com.selfach.dao.jooq.tables.User.USER;
}
