/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Photo extends org.jooq.impl.TableImpl<com.selfach.dao.jooq.tables.records.PhotoRecord> {

	private static final long serialVersionUID = -939892340;

	/**
	 * The singleton instance of <code>selfach.Photo</code>
	 */
	public static final com.selfach.dao.jooq.tables.Photo PHOTO = new com.selfach.dao.jooq.tables.Photo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.selfach.dao.jooq.tables.records.PhotoRecord> getRecordType() {
		return com.selfach.dao.jooq.tables.records.PhotoRecord.class;
	}

	/**
	 * The column <code>selfach.Photo.id</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.PhotoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>selfach.Photo.userId</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.PhotoRecord, java.lang.Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>selfach.Photo.created</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.PhotoRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>selfach.Photo.cameraId</code>.
	 */
	public final org.jooq.TableField<com.selfach.dao.jooq.tables.records.PhotoRecord, java.lang.Integer> CAMERAID = createField("cameraId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>selfach.Photo</code> table reference
	 */
	public Photo() {
		this("Photo", null);
	}

	/**
	 * Create an aliased <code>selfach.Photo</code> table reference
	 */
	public Photo(java.lang.String alias) {
		this(alias, com.selfach.dao.jooq.tables.Photo.PHOTO);
	}

	private Photo(java.lang.String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.PhotoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Photo(java.lang.String alias, org.jooq.Table<com.selfach.dao.jooq.tables.records.PhotoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.selfach.dao.jooq.Selfach.SELFACH, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.selfach.dao.jooq.tables.records.PhotoRecord, java.lang.Integer> getIdentity() {
		return com.selfach.dao.jooq.Keys.IDENTITY_PHOTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.PhotoRecord> getPrimaryKey() {
		return com.selfach.dao.jooq.Keys.KEY_PHOTO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.PhotoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.selfach.dao.jooq.tables.records.PhotoRecord>>asList(com.selfach.dao.jooq.Keys.KEY_PHOTO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.PhotoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.selfach.dao.jooq.tables.records.PhotoRecord, ?>>asList(com.selfach.dao.jooq.Keys.PHOTO_IBFK_1, com.selfach.dao.jooq.Keys.PHOTO_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.selfach.dao.jooq.tables.Photo as(java.lang.String alias) {
		return new com.selfach.dao.jooq.tables.Photo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.selfach.dao.jooq.tables.Photo rename(java.lang.String name) {
		return new com.selfach.dao.jooq.tables.Photo(name, null);
	}
}
