/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhotoRecord extends org.jooq.impl.UpdatableRecordImpl<com.selfach.dao.jooq.tables.records.PhotoRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = 1996329703;

	/**
	 * Setter for <code>selfach.Photo.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>selfach.Photo.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>selfach.Photo.userId</code>.
	 */
	public void setUserid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>selfach.Photo.userId</code>.
	 */
	public java.lang.Integer getUserid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>selfach.Photo.created</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>selfach.Photo.created</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>selfach.Photo.cameraId</code>.
	 */
	public void setCameraid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>selfach.Photo.cameraId</code>.
	 */
	public java.lang.Integer getCameraid() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.selfach.dao.jooq.tables.Photo.PHOTO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.selfach.dao.jooq.tables.Photo.PHOTO.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return com.selfach.dao.jooq.tables.Photo.PHOTO.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.selfach.dao.jooq.tables.Photo.PHOTO.CAMERAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getCameraid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PhotoRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PhotoRecord value2(java.lang.Integer value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PhotoRecord value3(java.sql.Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PhotoRecord value4(java.lang.Integer value) {
		setCameraid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PhotoRecord values(java.lang.Integer value1, java.lang.Integer value2, java.sql.Timestamp value3, java.lang.Integer value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PhotoRecord
	 */
	public PhotoRecord() {
		super(com.selfach.dao.jooq.tables.Photo.PHOTO);
	}

	/**
	 * Create a detached, initialised PhotoRecord
	 */
	public PhotoRecord(java.lang.Integer id, java.lang.Integer userid, java.sql.Timestamp created, java.lang.Integer cameraid) {
		super(com.selfach.dao.jooq.tables.Photo.PHOTO);

		setValue(0, id);
		setValue(1, userid);
		setValue(2, created);
		setValue(3, cameraid);
	}
}
