/**
 * This class is generated by jOOQ
 */
package com.selfach.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CameraraitingRecord extends org.jooq.impl.UpdatableRecordImpl<CameraraitingRecord> implements org.jooq.Record3<Integer, Integer, Integer> {

	private static final long serialVersionUID = 581186997;

	/**
	 * Setter for <code>selfach.CameraRaiting.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>selfach.CameraRaiting.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>selfach.CameraRaiting.cameraId</code>.
	 */
	public void setCameraid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>selfach.CameraRaiting.cameraId</code>.
	 */
	public Integer getCameraid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>selfach.CameraRaiting.raiting</code>.
	 */
	public void setRaiting(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>selfach.CameraRaiting.raiting</code>.
	 */
	public Integer getRaiting() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, Integer, Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<Integer, Integer, Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field1() {
		return com.selfach.dao.jooq.tables.Cameraraiting.CAMERARAITING.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field2() {
		return com.selfach.dao.jooq.tables.Cameraraiting.CAMERARAITING.CAMERAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Integer> field3() {
		return com.selfach.dao.jooq.tables.Cameraraiting.CAMERARAITING.RAITING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getCameraid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getRaiting();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CameraraitingRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CameraraitingRecord value2(Integer value) {
		setCameraid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CameraraitingRecord value3(Integer value) {
		setRaiting(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CameraraitingRecord values(Integer value1, Integer value2, Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CameraraitingRecord
	 */
	public CameraraitingRecord() {
		super(com.selfach.dao.jooq.tables.Cameraraiting.CAMERARAITING);
	}

	/**
	 * Create a detached, initialised CameraraitingRecord
	 */
	public CameraraitingRecord(Integer id, Integer cameraid, Integer raiting) {
		super(com.selfach.dao.jooq.tables.Cameraraiting.CAMERARAITING);

		setValue(0, id);
		setValue(1, cameraid);
		setValue(2, raiting);
	}
}
