---
- name: Install Java 8
  hosts: amazon
  sudo: yes

  roles: 
    - java8

  tasks:
  - name: Install MySQL
    apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
    with_items:
      - python-mysqldb
      - mysql-server
      - mysql-client
 
  - name: allow remote connections
    lineinfile: dest=/etc/mysql/my.cnf regexp='^(.*)bind-address' line=# 

  - name: update mysql root password for all root accounts
    mysql_user: name=selfach host={{ item }} password={{ selfachDBPasword }}  priv=*.*:ALL,GRANT state=present
    with_items:
      - "%"
      - 127.0.0.1
      - ::1
      - localhost

  - name: restart machine
    command: shutdown -r now "Ansible updates triggered"
    async: 0
    poll: 0
    ignore_errors: true