/**
 * This class is generated by jOOQ
 */
package com.pokupaka.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<com.pokupaka.dao.jooq.tables.records.UserRecord> {

	private static final long serialVersionUID = -858910699;

	/**
	 * The singleton instance of <code>pokupaka.User</code>
	 */
	public static final com.pokupaka.dao.jooq.tables.User USER = new com.pokupaka.dao.jooq.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.pokupaka.dao.jooq.tables.records.UserRecord> getRecordType() {
		return com.pokupaka.dao.jooq.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>pokupaka.User.id</code>.
	 */
	public final org.jooq.TableField<com.pokupaka.dao.jooq.tables.records.UserRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>pokupaka.User.name</code>.
	 */
	public final org.jooq.TableField<com.pokupaka.dao.jooq.tables.records.UserRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(22).defaulted(true), this, "");

	/**
	 * The column <code>pokupaka.User.surname</code>.
	 */
	public final org.jooq.TableField<com.pokupaka.dao.jooq.tables.records.UserRecord, java.lang.String> SURNAME = createField("surname", org.jooq.impl.SQLDataType.VARCHAR.length(22).defaulted(true), this, "");

	/**
	 * Create a <code>pokupaka.User</code> table reference
	 */
	public User() {
		this("User", null);
	}

	/**
	 * Create an aliased <code>pokupaka.User</code> table reference
	 */
	public User(java.lang.String alias) {
		this(alias, com.pokupaka.dao.jooq.tables.User.USER);
	}

	private User(java.lang.String alias, org.jooq.Table<com.pokupaka.dao.jooq.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(java.lang.String alias, org.jooq.Table<com.pokupaka.dao.jooq.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.pokupaka.dao.jooq.Pokupaka.POKUPAKA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.pokupaka.dao.jooq.tables.records.UserRecord, java.lang.Integer> getIdentity() {
		return com.pokupaka.dao.jooq.Keys.IDENTITY_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.pokupaka.dao.jooq.tables.records.UserRecord> getPrimaryKey() {
		return com.pokupaka.dao.jooq.Keys.KEY_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.pokupaka.dao.jooq.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.pokupaka.dao.jooq.tables.records.UserRecord>>asList(com.pokupaka.dao.jooq.Keys.KEY_USER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.pokupaka.dao.jooq.tables.User as(java.lang.String alias) {
		return new com.pokupaka.dao.jooq.tables.User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.pokupaka.dao.jooq.tables.User rename(java.lang.String name) {
		return new com.pokupaka.dao.jooq.tables.User(name, null);
	}
}
